# -*- coding: utf-8 -*-
"""75k dataset (80:20,70:30,60:40)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mm-7oRA4WPEtjvbDM_2-UZjDOixhGAQT
"""

!pip install xgboost
!pip install scikit-learn seaborn
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

!pip install scikit-learn seaborn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import HistGradientBoostingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("train_80_percent_dataset.csv")
target_column = df.columns[-1]
X = df.drop(columns=[target_column])
y = df[target_column]
X = X[['wt_psic','dpsic','plddt','mt_psic','plddt_mean','kdHydrophobicity_DELTAmn','Volume_(A3)_n']]

X['psic_ratio'] = X['mt_psic'] / (X['wt_psic'] + 1e-5)
X['plddt_diff'] = X['plddt'] - X['plddt_mean']

#This is for training 80 and testing 20 (80:20)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    return acc, prec, rec, f1, cm, y_prob

hgb_model = HistGradientBoostingClassifier(max_iter=300, learning_rate=0.05, max_depth=6, random_state=42)
hgb_model.fit(X_train, y_train)
hgb_acc, hgb_prec, hgb_rec, hgb_f1, hgb_cm, hgb_prob = evaluate_model(hgb_model, X_test, y_test)

gb_model = GradientBoostingClassifier(n_estimators=300, learning_rate=0.05, max_depth=3, random_state=42)
gb_model.fit(X_train, y_train)
gb_acc, gb_prec, gb_rec, gb_f1, gb_cm, gb_prob = evaluate_model(gb_model, X_test, y_test)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=12,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_acc, rf_prec, rf_rec, rf_f1, rf_cm, rf_prob = evaluate_model(rf_model, X_test, y_test)

scale_pos_weight = len(y[y==0]) / len(y[y==1])
xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.85,
    colsample_bytree=0.85,
    gamma=0.1,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_acc, xgb_prec, xgb_rec, xgb_f1, xgb_cm, xgb_prob = evaluate_model(xgb_model, X_test, y_test)

import pickle
pickle.dump(xgb_model, open("model.pkl", "wb"))

from google.colab import files
files.download("model.pkl")

from sklearn.metrics import roc_auc_score

hgb_auc = roc_auc_score(y_test, hgb_prob)
gb_auc = roc_auc_score(y_test, gb_prob)

comparison = pd.DataFrame({
    "Model": ["HistGradientBoosting","Gradient Boosting"],
    "Accuracy": [hgb_acc, gb_acc],
    "ROC_AUC": [hgb_auc, gb_auc]
})
comparison

from sklearn.metrics import roc_auc_score

rf_auc = roc_auc_score(y_test, rf_prob)
xgb_auc = roc_auc_score(y_test, xgb_prob)

comparison_extra = pd.DataFrame({
    "Model": ["Random Forest","XGBoost"],
    "Accuracy": [rf_acc, xgb_acc],
    "ROC_AUC": [rf_auc, xgb_auc]
})
comparison_extra

import seaborn as sns
import matplotlib.pyplot as plt
def plot_model_results(name, y_test, y_pred, acc, prec, f1, cm):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d')
    plt.title(f"{name}\nAcc:{acc:.3f}  Prec:{prec:.3f}  F1:{f1:.3f}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

rf_pred = rf_model.predict(X_test)
plot_model_results(
    "Random Forest",
    y_test,
    rf_pred,
    rf_acc,
    rf_prec,
    rf_f1,
    rf_cm
)
xgb_pred = xgb_model.predict(X_test)
plot_model_results(
    "XGBoost",
    y_test,
    xgb_pred,
    xgb_acc,
    xgb_prec,
    xgb_f1,
    xgb_cm
)
gb_pred = gb_model.predict(X_test)
plot_model_results(
    "Gradient Boosting",
    y_test,
    gb_pred,
    gb_acc,
    gb_prec,
    gb_f1,
    gb_cm
)
hgb_pred = hgb_model.predict(X_test)
plot_model_results(
    "HistGradientBoosting",
    y_test,
    hgb_pred,
    hgb_acc,
    hgb_prec,
    hgb_f1,
    hgb_cm
)

comparison_final = pd.DataFrame({
    "Model": [
        "Random Forest",
        "XGBoost",
        "HistGradientBoosting",
        "Gradient Boosting"
    ],
    "Accuracy": [
        rf_acc, xgb_acc, hgb_acc, gb_acc
    ],
    "Precision": [
        rf_prec, xgb_prec, hgb_prec, gb_prec
    ],
    "Recall": [
        rf_rec, xgb_rec, hgb_rec, gb_rec
    ],
    "F1 Score": [
        rf_f1, xgb_f1, hgb_f1, gb_f1
    ]
})
comparison_final

rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_prob)
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_prob)
hgb_fpr, hgb_tpr, _ = roc_curve(y_test, hgb_prob)
gb_fpr, gb_tpr, _ = roc_curve(y_test, gb_prob)

rf_auc = auc(rf_fpr, rf_tpr)
xgb_auc = auc(xgb_fpr, xgb_tpr)
hgb_auc = auc(hgb_fpr, hgb_tpr)
gb_auc = auc(gb_fpr, gb_tpr)

plt.figure()

plt.plot(rf_fpr, rf_tpr, label=f"Random Forest (AUC={rf_auc:.3f})")
plt.plot(xgb_fpr, xgb_tpr, label=f"XGBoost (AUC={xgb_auc:.3f})")
plt.plot(hgb_fpr, hgb_tpr, label=f"HistGradientBoosting (AUC={hgb_auc:.3f})")
plt.plot(gb_fpr, gb_tpr, label=f"Gradient Boosting (AUC={gb_auc:.3f})")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")

plt.legend()
plt.show()

#test_dataset = X_test.copy()
#test_dataset[target_column] = y_test
#test_dataset.to_csv("test_20_percent_dataset.csv", index=False)

#from google.colab import files
#files.download("test_20_percent_dataset.csv")

#This is for training 70 and testing 30 (70:30)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=12,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_acc, rf_prec, rf_rec, rf_f1, rf_cm, rf_prob = evaluate_model(rf_model, X_test, y_test)

scale_pos_weight = len(y[y==0]) / len(y[y==1])
xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.85,
    colsample_bytree=0.85,
    gamma=0.1,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42
)
xgb_model.fit(X_train, y_train)
xgb_acc, xgb_prec, xgb_rec, xgb_f1, xgb_cm, xgb_prob = evaluate_model(xgb_model, X_test, y_test)

hgb_model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)
hgb_model.fit(X_train, y_train)
hgb_acc, hgb_prec, hgb_rec, hgb_f1, hgb_cm, hgb_prob = evaluate_model(hgb_model, X_test, y_test)

gb_model = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)
gb_model.fit(X_train, y_train)
gb_acc, gb_prec, gb_rec, gb_f1, gb_cm, gb_prob = evaluate_model(gb_model, X_test, y_test)

import seaborn as sns
import matplotlib.pyplot as plt

def plot_model_results(name, acc, prec, rec, f1, cm):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d')
    plt.title(f"{name}\nAcc:{acc:.3f}  Prec:{prec:.3f}  Rec:{rec:.3f}  F1:{f1:.3f}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plot_model_results("Random Forest", rf_acc, rf_prec, rf_rec, rf_f1, rf_cm)
plot_model_results("XGBoost", xgb_acc, xgb_prec, xgb_rec, xgb_f1, xgb_cm)
plot_model_results("HistGradientBoosting", hgb_acc, hgb_prec, hgb_rec, hgb_f1, hgb_cm)
plot_model_results("Gradient Boosting", gb_acc, gb_prec, gb_rec, gb_f1, gb_cm)

comparison_final = pd.DataFrame({
    "Model": [
        "Random Forest",
        "XGBoost",
        "HistGradientBoosting",
        "Gradient Boosting"
    ],
    "Accuracy": [
        rf_acc, xgb_acc, hgb_acc, gb_acc
    ],
    "Precision": [
        rf_prec, xgb_prec, hgb_prec, gb_prec
    ],
    "Recall": [
        rf_rec, xgb_rec, hgb_rec, gb_rec
    ],
    "F1 Score": [
        rf_f1, xgb_f1, hgb_f1, gb_f1
    ]
})
comparison_final

rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_prob)
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_prob)
hgb_fpr, hgb_tpr, _ = roc_curve(y_test, hgb_prob)
gb_fpr, gb_tpr, _ = roc_curve(y_test, gb_prob)

rf_auc = auc(rf_fpr, rf_tpr)
xgb_auc = auc(xgb_fpr, xgb_tpr)
hgb_auc = auc(hgb_fpr, hgb_tpr)
gb_auc = auc(gb_fpr, gb_tpr)

plt.figure()

plt.plot(rf_fpr, rf_tpr, label=f"Random Forest (AUC={rf_auc:.3f})")
plt.plot(xgb_fpr, xgb_tpr, label=f"XGBoost (AUC={xgb_auc:.3f})")
plt.plot(hgb_fpr, hgb_tpr, label=f"HistGradientBoosting (AUC={hgb_auc:.3f})")
plt.plot(gb_fpr, gb_tpr, label=f"Gradient Boosting (AUC={gb_auc:.3f})")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")

plt.legend()
plt.show()

#test_dataset = X_test.copy()
#test_dataset[target_column] = y_test
#test_dataset.to_csv("test_30_percent_dataset.csv", index=False)

#from google.colab import files
#files.download("test_30_percent_dataset.csv")

#This is for training 60 and testing 40 (60:40)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.4,
    random_state=42,
    stratify=y
)

rf_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=12,
    min_samples_split=5,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)
rf_acc, rf_prec, rf_rec, rf_f1, rf_cm, rf_prob = evaluate_model(rf_model, X_test, y_test)

scale_pos_weight = len(y[y==0]) / len(y[y==1])
xgb_model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.85,
    colsample_bytree=0.85,
    gamma=0.1,
    scale_pos_weight=scale_pos_weight,
    eval_metric='logloss',
    random_state=42
)
xgb_model.fit(X_train, y_train)
xgb_acc, xgb_prec, xgb_rec, xgb_f1, xgb_cm, xgb_prob = evaluate_model(xgb_model, X_test, y_test)

hgb_model = HistGradientBoostingClassifier(
    max_iter=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)
hgb_model.fit(X_train, y_train)
hgb_acc, hgb_prec, hgb_rec, hgb_f1, hgb_cm, hgb_prob = evaluate_model(hgb_model, X_test, y_test)

gb_model = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)
gb_model.fit(X_train, y_train)
gb_acc, gb_prec, gb_rec, gb_f1, gb_cm, gb_prob = evaluate_model(gb_model, X_test, y_test)

comparison_final = pd.DataFrame({
    "Model": [
        "Random Forest",
        "XGBoost",
        "HistGradientBoosting",
        "Gradient Boosting"
    ],
    "Accuracy": [
        rf_acc, xgb_acc, hgb_acc, gb_acc
    ],
    "Precision": [
        rf_prec, xgb_prec, hgb_prec, gb_prec
    ],
    "Recall": [
        rf_rec, xgb_rec, hgb_rec, gb_rec
    ],
    "F1 Score": [
        rf_f1, xgb_f1, hgb_f1, gb_f1
    ]
})
comparison_final

import seaborn as sns
import matplotlib.pyplot as plt
def plot_model_results(name, acc, prec, rec, f1, cm):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d')
    plt.title(f"{name}\nAcc:{acc:.3f}  Prec:{prec:.3f}  Rec:{rec:.3f}  F1:{f1:.3f}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plot_model_results("Random Forest", rf_acc, rf_prec, rf_rec, rf_f1, rf_cm)
plot_model_results("XGBoost", xgb_acc, xgb_prec, xgb_rec, xgb_f1, xgb_cm)
plot_model_results("HistGradientBoosting", hgb_acc, hgb_prec, hgb_rec, hgb_f1, hgb_cm)
plot_model_results("Gradient Boosting", gb_acc, gb_prec, gb_rec, gb_f1, gb_cm)

rf_fpr, rf_tpr, _ = roc_curve(y_test, rf_prob)
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, xgb_prob)
hgb_fpr, hgb_tpr, _ = roc_curve(y_test, hgb_prob)
gb_fpr, gb_tpr, _ = roc_curve(y_test, gb_prob)

rf_auc = auc(rf_fpr, rf_tpr)
xgb_auc = auc(xgb_fpr, xgb_tpr)
hgb_auc = auc(hgb_fpr, hgb_tpr)
gb_auc = auc(gb_fpr, gb_tpr)

plt.figure()

plt.plot(rf_fpr, rf_tpr, label=f"Random Forest (AUC={rf_auc:.3f})")
plt.plot(xgb_fpr, xgb_tpr, label=f"XGBoost (AUC={xgb_auc:.3f})")
plt.plot(hgb_fpr, hgb_tpr, label=f"HistGradientBoosting (AUC={hgb_auc:.3f})")
plt.plot(gb_fpr, gb_tpr, label=f"Gradient Boosting (AUC={gb_auc:.3f})")

plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")

plt.legend()
plt.show()

#test_dataset = X_test.copy()
#test_dataset[target_column] = y_test
#test_dataset.to_csv("test_40_percent_dataset.csv", index=False)

#from google.colab import files
#files.download("test_40_percent_dataset.csv")